exports_files([
    "pybind_extension.py.tpl",
    "pywrap.bzl",
])

py_binary(
    name = "def_file_filter_tool",
    srcs = [":def_file_filter_tool.py"],
    visibility = ["//visibility:public"],
)
