exports_files(["static_resource.txt"])

cc_binary(
    name = "data_binary",
    srcs = ["data_binary.cc"],
    copts = ["-D_GLIBCXX_USE_CXX11_ABI=0"],
    visibility = ["//visibility:public"],
    deps = [],
)
